language: python
python:
  - 2.7
before_install:
  - export DISPLAY=:99
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r test-requirements.txt
  - pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/base.txt
  - pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/test.txt
  - pip install -r $VIRTUAL_ENV/src/xblock/requirements.txt
script:
  - pep8 --max-line-length=100 activetable
  - pylint activetable
  - ./run_tests.py --with-coverage --cover-package=activetable
notifications:
  email: false
addons:
  firefox: 36.0
